@startuml

title __RESTSERVICE's Class Diagram__\n

  namespace de.cookiebook.restservice {
    enum Category {
      DESSERT
      GETRÄNKE
      GRUNDREZEPTE
      HAUPTGERICHTE
      SONSTIGES
      VORSPEISE
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.Recipe {
        - calories : Integer
        - category : Category
        - difficultyLevel : Integer
        - duration : Integer
        - id : Long
        - ingredients : String
        - link : String
        - material : String
        - otherInformation : String
        - steps : String
        - tags : List<Tag>
        - title : String
        + Recipe()
        + Recipe()
        + addTag()
        + getCalories()
        + getCategory()
        + getDifficultyLevel()
        + getDuration()
        + getId()
        + getIngredients()
        + getLink()
        + getMaterial()
        + getOtherInformation()
        + getSteps()
        + getTags()
        + getTitle()
        + setCalories()
        + setCategory()
        + setDifficultyLevel()
        + setDuration()
        + setIngredients()
        + setLink()
        + setMaterial()
        + setOtherInformation()
        + setSteps()
        + setTags()
        + setTitle()
        + toString()
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RecipeController {
        ~ recipeRepository : RecipeRepository
        ~ tagRepository : TagRepository
        + RecipeController()
        + addRecipe()
        + deleteRecipe()
        + editRecipe()
        + readRecipe()
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.RecipeRepository {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RestServiceApplication {
        {static} + main()
    }
  }
  

  namespace de.cookiebook.restservice {
    enum Status {
      FAILURE
      SUCCESS
      USER_ALREADY_EXISTS
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.Tag {
        - id : long
        - taggedRecipes : List<Recipe>
        - title : String
        + Tag()
        + Tag()
        + addRecipe()
        + getId()
        + getTitle()
        + setTitle()
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.TagRepository {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.User {
        - email : String
        - id : long
        - loggedIn : boolean
        - password : String
        + User()
        + User()
        + equals()
        + getEmail()
        + getId()
        + getPassword()
        + hashCode()
        + isLoggedIn()
        + setEmail()
        + setLoggedIn()
        + setPassword()
        + toString()
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.UserController {
        ~ userRepository : UserRepository
        + getUsers()
        + logUserOut()
        + loginUser()
        + registerUser()
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.UserRepository {
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
