version: "1.0"
services:
  sonarqube:
    image: docker.mirror.markant.com/sonarqube:8.5.1-community
    container_name: sonar
    networks:
      - overlay
    ports:
      - "9000:9000"
    volumes:
      - sonardata:/opt/sonarqube/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  permission-client:
    container_name: client
    networks:
      - overlay
    volumes:
      - /c/cloud-service/sonarqube-permission-client/teams:/app/teams
    image: docker.markant.com/sohle/sonarqube-permission-client/client:1.0
    env_file:
      - webservice.env

networks:
  overlay:
    external: true

volumes:
  sonardata: