@startuml

title __REST-SERVICE's Class Diagram__\n

  namespace de.cookiebook.restservice {
    enum Category {
    }
  }
  

  namespace de.cookiebook.restservice {
    enum Category {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.Recipe {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.Recipe {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RecipeController {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RecipeController {
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.RecipeRepository {
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.RecipeRepository {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RestServiceApplication {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RestServiceApplication {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RestServiceApplicationTests {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.RestServiceApplicationTests {
    }
  }
  

  namespace de.cookiebook.restservice {
    enum Status {
    }
  }
  

  namespace de.cookiebook.restservice {
    enum Status {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.Tag {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.Tag {
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.TagRepository {
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.TagRepository {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.User {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.User {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.UserController {
    }
  }
  

  namespace de.cookiebook.restservice {
    class de.cookiebook.restservice.UserController {
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.UserRepository {
    }
  }
  

  namespace de.cookiebook.restservice {
    interface de.cookiebook.restservice.UserRepository {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    class src.main.java.de.cookiebook.restservice.Recipe {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    class src.main.java.de.cookiebook.restservice.RecipeController {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    interface src.main.java.de.cookiebook.restservice.RecipeRepository {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    class src.main.java.de.cookiebook.restservice.RestServiceApplication {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    enum Status {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    class src.main.java.de.cookiebook.restservice.User {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    class src.main.java.de.cookiebook.restservice.UserController {
    }
  }
  

  namespace src.main.java.de.cookiebook.restservice {
    interface src.main.java.de.cookiebook.restservice.UserRepository {
    }
  }
  

  namespace src.test.java.de.cookiebook.restservice {
    class src.test.java.de.cookiebook.restservice.RestServiceApplicationTests {
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
