name: Build and Test


on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: gradle build

      - name: Run Tests
        run : gradle test

      - name: Build Project
        run: gradle assemble

#- name: Build and analyze
#env:
#SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
# run: ./gradlew build sonarqube --info
